(() => {
  'use strict';
  const PREFIX='campus-buddy.unified-session.v1:';
  const APPS=[{id:'wallet',name:'Campus Wallet',icon:'W',copy:'Balance and transaction history.'},{id:'faucet',name:'Campus Faucet',icon:'F',copy:'Claim demo TEST funds.'},{id:'bookstore',name:'Campus Bookstore',icon:'B',copy:'Buy items and unlock Buddy looks.'}];
  const PRODUCTS=[{id:'campus-hoodie',name:'Campus Hoodie',price:40,unlock:{value:'hoodie',label:'Soft hoodie'}},{id:'light-jacket',name:'Light Jacket',price:55,unlock:{value:'jacket',label:'Light jacket'}},{id:'study-notebook',name:'Study Notebook',price:15,unlock:null}];
  let session=null,active='dashboard',toastTimer=null;
  const $=s=>document.querySelector(s);
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const amount=v=>`${Number(v).toFixed(2)} TEST`;
  const email=()=>($('#reviewEmail')?.textContent||$('#studentEmail')?.value||'student@university.edu').trim().toLowerCase();
  const key=()=>PREFIX+email();
  function fresh(){return{email:email(),balance:0,faucetClaimed:false,transactions:[],orders:[],entitlements:[]};}
  function load(){try{const v=JSON.parse(localStorage.getItem(key())||'null');session=v?.email===email()?v:fresh();}catch{session=fresh();}return session;}
  function save(){try{localStorage.setItem(key(),JSON.stringify(session));}catch{}window.dispatchEvent(new CustomEvent('campus-session-changed',{detail:{session}}));}
  function notify(text){const el=$('#toast');if(!el)return;el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,2600);}
  function addTx(delta,label){session.transactions.unshift({id:`TX-${Date.now().toString(36).toUpperCase()}`,amount:delta,label,at:new Date().toLocaleString()});}
  function dashboard(){return `<div class="campus-dashboard-head"><div><span>Connected account</span><strong>${esc(session.email)}</strong></div><div class="dashboard-balance"><span>Campus Wallet</span><strong>${amount(session.balance)}</strong></div></div><div class="campus-app-grid">${APPS.map(a=>`<button class="campus-app-card" type="button" data-open-campus-app="${a.id}"><b>${a.icon}</b><span><strong>${a.name}</strong><small>${a.copy}</small></span></button>`).join('')}</div>`;}
  function wallet(){const rows=session.transactions.length?session.transactions.map(t=>`<div class="wallet-row"><span><strong>${esc(t.label)}</strong><small>${esc(t.at)}</small></span><b class="${t.amount>=0?'positive':'negative'}">${t.amount>=0?'+':''}${amount(t.amount)}</b></div>`).join(''):'<div class="mini-empty">Wallet is empty. Open Campus Faucet to add test funds.</div>';return `<section class="mini-app"><div class="wallet-overview"><span>Available balance</span><strong>${amount(session.balance)}</strong><small>${esc(session.email)}</small></div><h3>Recent activity</h3><div class="wallet-list">${rows}</div></section>`;}
  function faucet(){return `<section class="mini-app"><div class="app-status-pill">Wallet connected</div><h2>Campus Faucet</h2><p>Connected as <strong>${esc(session.email)}</strong></p><div class="faucet-claim"><span>Demo allocation</span><strong>100.00 TEST</strong><button class="mini-primary" type="button" data-faucet-claim ${session.faucetClaimed?'disabled':''}>${session.faucetClaimed?'Already claimed':'Claim 100 TEST'}</button></div><p class="mini-note">Simulated test-network value only.</p></section>`;}
  function bookstore(){return `<section class="mini-app"><div class="store-top"><div><span>Connected wallet</span><strong>${amount(session.balance)}</strong></div><small>${esc(session.email)}</small></div><div class="store-grid">${PRODUCTS.map(p=>{const owned=p.unlock&&session.entitlements.some(e=>e.productId===p.id);return `<article class="store-card"><div class="store-art">${p.unlock?'★':'▤'}</div><span>${p.unlock?'Buddy collectible':'Campus item'}</span><h3>${p.name}</h3><strong>${amount(p.price)}</strong><button type="button" data-buy-product="${p.id}" ${owned?'disabled':''}>${owned?'Owned':'Buy'}</button>${owned?`<button class="mini-secondary" type="button" data-equip-product="${p.id}">Equip on Buddy</button>`:''}</article>`}).join('')}</div></section>`;}
  function render(view=active){active=view;const title=view==='dashboard'?'Apps Dashboard':APPS.find(a=>a.id===view)?.name||'Campus Apps';$('#campusAppsTitle').textContent=title;$('#campusAppsBack').hidden=view==='dashboard';$('#campusAppsContent').innerHTML=view==='dashboard'?dashboard():view==='wallet'?wallet():view==='faucet'?faucet():bookstore();}
  function open(view='dashboard'){load();render(view);$('#campusAppsShell').hidden=false;$('#campusAppsClose').focus();}
  function close(){$('#campusAppsShell').hidden=true;}
  function claim(){if(session.faucetClaimed)return;session.faucetClaimed=true;session.balance+=100;addTx(100,'Campus Faucet allocation');save();render('faucet');notify('100 TEST added to Campus Wallet.');}
  function buy(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;if(session.balance<p.price){notify('Not enough TEST. Visit Campus Faucet first.');return;}session.balance-=p.price;addTx(-p.price,`Campus Bookstore · ${p.name}`);session.orders.unshift({id:`ORDER-${Date.now().toString(36).toUpperCase()}`,productId:p.id,name:p.name,price:p.price});if(p.unlock&&!session.entitlements.some(e=>e.productId===p.id))session.entitlements.push({productId:p.id,label:p.unlock.label,outfit:p.unlock.value});save();render('bookstore');notify(`${p.name} purchased${p.unlock?' and unlocked for Buddy.':''}`);}
  function equip(id){const e=session.entitlements.find(x=>x.productId===id);if(!e)return;const button=document.querySelector(`[data-outfit="${e.outfit}"]`);button?.click();notify(`${e.label} equipped on Buddy.`);}
  function setupHost(){const computer=document.querySelector('.game-dock [data-panel="campusweb"]');if(computer){computer.querySelector('span').textContent='Computer';computer.firstChild.textContent='▦';computer.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open('dashboard');},true);}document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#campusAppsShell').hidden){e.preventDefault();close();}});}
  document.addEventListener('click',e=>{const launch=e.target.closest('[data-open-campus-app]');if(launch){render(launch.dataset.openCampusApp);return;}if(e.target.closest('#campusAppsBack')){render('dashboard');return;}if(e.target.closest('#campusAppsClose')){close();return;}if(e.target.closest('[data-faucet-claim]')){claim();return;}const buyButton=e.target.closest('[data-buy-product]');if(buyButton){buy(buyButton.dataset.buyProduct);return;}const equipButton=e.target.closest('[data-equip-product]');if(equipButton)equip(equipButton.dataset.equipProduct);});
  setupHost();
  window.CampusUnifiedApps=Object.freeze({open,close,getSession:()=>session||load()});
})();